export const CHANGE_USER_REGISTER = "CHANGE_USER_REGISTER";
export const CHANGE_TEXT_BUTTON = "CHANGE_TEXT_BUTTON";
export const SAVE_CHECKED = "SAVE_CHECKED";
export const OPEN_CLOSE_FORM = "OPEN_CLOSE_FORM";
export const CHANGE_RENDER_OPTION = "CHANGE_RENDER_OPTION"